Deploy berks diff (#27)
* Squashed commit of the following:

* use higher golang version

* Add golang metadata

* remove dead cookbook

* only use upstart on trusty

* use systemd on xenial

* support more network options

* update gearman version

* fix ppa

* overwrite existing package contents

* fix unzip dir

* pre-identify proper network interface

* mirror opsworks recipes

* continue to use consul interface

* use databags to get required variables

* catch databag errors

* add self signed certs

* use systemd for consul

* don’t install old gearman version

* add missing packages

* update mysql

* use tmp dir for dumps

* stop using apt for phpmyadmin

diff --git a/jb_db/templates/default/jbdb_import.erb b/jb_db/templates/default/jbdb_import.erb
--- a/jb_db/templates/default/jbdb_import.erb
+++ b/jb_db/templates/default/jbdb_import.erb
@@ -14,21 +14,10 @@ else
   database=$1;
 fi
 
-# If we're importing any schema we need to create the db
-if [ "$2" == "--create" ] || [ "$2" == "--schema-only" ]
-then
-  echo "CREATE DATABASE IF NOT EXISTS $database" | mysql -u${user} -p${password};
-
-  if [ $? != 0 ]
-  then
-    echo "Failed to create database $database";
-    exit 1;
-  fi
-fi
-
 # Determine which file to get from S3
 case "$2" in
   --create)
+    echo "DROP DATABASE IF EXISTS ${database}" | mysql -u${user} -p${password} > /dev/null 2&>1;
     type="dump";
     ;;
 
@@ -57,9 +46,22 @@ case "$2" in
     ;;
 esac
 
+# If we're importing any schema we need to create the db
+if [ "$2" == "--create" ] || [ "$2" == "--schema-only" ]
+then
+  echo "CREATE DATABASE IF NOT EXISTS $database" | mysql -u${user} -p${password};
+
+  if [ $? != 0 ]
+  then
+    echo "Failed to create database $database";
+    exit 1;
+  fi
+fi
+
 # Copy the file from S3
 file_name="${type}_${day}.sql.gz";
-home_dir="/home/vagrant"
+home_dir="/tmp"
+rm "${home_dir}/${file_name}" > /dev/null 2&>1
 aws s3 cp "${base_url}/${file_name}" "${home_dir}/${file_name}";
 
 # Check if the copy was successful
